repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      # - id: reorder-python-imports
      #   name: Reorder python imports
      #   entry: reorder-python-imports
      #   language: system
      #   types: [python]
      # - id: flake8
      #   name: flake8
      #   entry: flake8
      #   language: system
      #   types: [python]
      #   args: ["--config=.flake8"]
      #   require_serial: true
      - id: no-commit-to-branch
        name: Prevent commits to dev / master
        entry: no-commit-to-branch
        language: python
        args: ["-b", dev, "-b", master, "-b", main]
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
